In [34]:
print("Hello World")

Hello World


In [35]:
# Operators in Python
# 1. Arithmetic Operators(+,-,*,/,//,%,**)
# 2. Logical Operators(and, or, not)
# 3. Membership Operators(in, not in)
# 4. Identity Operators(is, is not)

In [36]:
5/2

2.5

In [37]:
int(1234/10)

123

In [38]:
1234//10

123

In [39]:
#5****2

In [40]:
a=10
b=20

if (a>b and a%2==0):
    print("true")
else:
    print("false")

false


In [41]:
a=10
b=20

if (a>b or a%2==0):
    print("true")
else:
    print("false")

true


In [42]:
a=10
b=20

if not(a>b and a%2==0):
    print("true")
else:
    print("false")

true


In [43]:
a=0
not a

True

In [44]:
li=[2,4,1,6]

1 in li

True

In [45]:
7 not in li

True

In [46]:
a=10
b=30
c= ++a + b
print(c)

40


In [47]:
a++ + b

40

In [48]:
a++b

40

In [49]:
++a

10

In [50]:
a++ + 10

20

In [51]:
a

10

In [52]:
a+=50
a

60

In [53]:
id(a)

1725786443984

In [54]:
id(b)

1725786254544

In [55]:
a is b

False

In [56]:
a=60
b=60

a is b

True

In [57]:
# numpy is a python library used to perform numeric operations

In [58]:
import numpy as np

In [59]:
a=np.array([2,4,7])
print(a)

[2 4 7]


In [60]:
type(a)

numpy.ndarray

In [61]:
a.size

3

In [62]:
a.dtype

dtype('int32')

In [63]:
a.itemsize*a.size

12

In [64]:
a=np.array([[1,2],
            [3,4],
            [5,6]])

print(a)
print("shape of a:",a.shape)

[[1 2]
 [3 4]
 [5 6]]
shape of a: (3, 2)


In [65]:
a.sum()

21

In [66]:
a.sum(axis=1)

array([ 3,  7, 11])

In [67]:
a.sum(axis=0)

array([ 9, 12])

In [68]:
a.mean()

3.5

In [69]:
np.median(a)

3.5

In [70]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
b.shape

(10,)

In [72]:
b=b.reshape(5,2)

In [73]:
b,a

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [74]:
a=np.random.randint(1,100,(5,2))
a

array([[80, 51],
       [79, 60],
       [96, 92],
       [37, 94],
       [ 9, 69]])

In [75]:
a+b

array([[ 80,  52],
       [ 81,  63],
       [100,  97],
       [ 43, 101],
       [ 17,  78]])

In [76]:
a-b

array([[80, 50],
       [77, 57],
       [92, 87],
       [31, 87],
       [ 1, 60]])

In [77]:
a/b

C:\Users\ACER\AppData\Local\Temp/ipykernel_8116/1348051284.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([[        inf, 51.        ],
       [39.5       , 20.        ],
       [24.        , 18.4       ],
       [ 6.16666667, 13.42857143],
       [ 1.125     ,  7.66666667]])

In [78]:
a*b

array([[  0,  51],
       [158, 180],
       [384, 460],
       [222, 658],
       [ 72, 621]])

In [79]:
# a(5,2) b(5,2)
b=b.reshape(2,5)
np.matmul(a,b)

array([[ 255,  386,  517,  648,  779],
       [ 300,  439,  578,  717,  856],
       [ 460,  648,  836, 1024, 1212],
       [ 470,  601,  732,  863,  994],
       [ 345,  423,  501,  579,  657]])

In [80]:
a@b

array([[ 255,  386,  517,  648,  779],
       [ 300,  439,  578,  717,  856],
       [ 460,  648,  836, 1024, 1212],
       [ 470,  601,  732,  863,  994],
       [ 345,  423,  501,  579,  657]])

In [81]:
#calculate sum of diagonal
s=0
for i in range(len(a)):
    for j in range(len(a[0])):
        if i==j:
            s=s+a[i][j]
            
s

140

In [82]:
a.trace()

140